name: java_CI

on:
  push: 
   branches: [ "main" ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: gitleaks/gitleaks-action@v2    
      - name: scancod
        uses: gitleaks/gitleaks-action@v2
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: gitleaks/gitleaks-action@v2
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution:
          java-version:
          cache: maven
      - name: Build
        run: mvn -B clean verify
